# Generated by Django 3.0.6 on 2022-08-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onepost',
            name='abstract',
            field=models.TextField(default='abstract', max_length=256),
        ),
        migrations.AddField(
            model_name='onepost',
            name='imgurl',
            field=models.URLField(default='imgurl', max_length=256),
        ),
    ]
