# Generated by Django 3.0.6 on 2022-08-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20220801_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onepost',
            name='imgurl',
            field=models.URLField(default='https://s2.loli.net/2022/08/01/8KSLDNbVMiFxgI4.jpg', max_length=256),
        ),
    ]
